//! Tests for the RW4 section-directory walker.
//!
//! Two sources of truth are used:
//!
//! * the **committed synthetic fixture** `tests/fixtures/mini_rw4.rw4`
//!   (392 bytes, generated by `tests/fixtures/gen_fixtures.py::build_rw4`) for
//!   the forward assertions — every header field, every row field, the exact
//!   `describe()` string, completeness, and the truncation sweep;
//! * an in-module **builder** that emits a record from scratch, so the layout is
//!   proven in the *forward* direction too and every error variant can be
//!   provoked deliberately rather than by hoping a mutation lands somewhere
//!   interesting.
//!
//! `describe()`'s expected string was produced by
//! `python3 tools/spore/rw4/rw4.py tests/fixtures/mini_rw4.rw4`
//! (equivalently `rw4.describe(bytes)`), which `tests/test_rw4.py` also diffs
//! against the C++ walker over all 1,131 real records.

use super::*;

const FIXTURE: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/fixtures/mini_rw4.rw4"
));

/// `rw4.py::describe` output for the committed fixture, character for character.
const FIXTURE_DESCRIBE: &str =
    "0x1 obj=1 sec=3 buf=80 | 10030 d=0x138 s=12 | 20003 d=0x144 s=44 | 40001 d=0x170 s=24";

fn fixture() -> Rw4 {
    match parse(FIXTURE) {
        Ok(r) => r,
        Err(e) => panic!("committed fixture must parse, got {e}"),
    }
}

// ---------------------------------------------------------------- helpers

fn put_u32(buf: &mut [u8], off: usize, v: u32) {
    buf[off..off + 4].copy_from_slice(&v.to_le_bytes());
}

fn put_i32(buf: &mut [u8], off: usize, v: i32) {
    buf[off..off + 4].copy_from_slice(&v.to_le_bytes());
}

fn read_u32(buf: &[u8], off: usize) -> u32 {
    u32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]])
}

/// One section row to emit.
#[derive(Debug, Clone)]
struct RowSpec {
    tc: u32,
    payload: Vec<u8>,
    align: i32,
    unknown_04: u32,
    /// `Some` to force a specific `type_code_index` instead of the derived one.
    tc_index: Option<i32>,
    /// `Some` to force a specific `size` instead of `payload.len()`.
    size: Option<i32>,
    /// `Some` to force a specific raw `data_pointer`.
    data_pointer: Option<u32>,
}

impl RowSpec {
    fn new(tc: u32, payload: Vec<u8>) -> Self {
        Self {
            tc,
            payload,
            align: 1,
            unknown_04: 0,
            tc_index: None,
            size: None,
            data_pointer: None,
        }
    }
}

/// Emits a syntactically valid RW4 record, with every field overridable so a
/// single structural defect can be isolated.
///
/// Layout produced (nothing is hard-coded; the builder computes it):
///
/// ```text
/// 0x00          header: 28 B magic + words through 0x4C, zero-padded to 0x98
/// 0x98          SectionManifest (0x1C B), o1 = 0x1C + types_gap
/// <types_gap>   zero bytes
/// 0x98 + o1     SectionTypes: TYPES_TC, n, codes[]
/// rows          SECTION_ROW_SIZE B each
/// arena         row payloads back to back
/// <trailing>    zero bytes
/// ```
#[derive(Debug, Clone)]
struct Builder {
    file_type: u32,
    object_count: u32,
    rows: Vec<RowSpec>,
    section_count: Option<u32>,
    manifest_tc: u32,
    types_tc: u32,
    types_gap: usize,
    n_types: Option<u32>,
    extra_type_codes: Vec<u32>,
    buffer_pointer: Option<u32>,
    buffer_size: Option<u32>,
    section_info_pointer: Option<u32>,
    manifest_o1: Option<u32>,
    /// Zero bytes between the last emitted row and the arena. Lets a record
    /// declare more `section_count` rows than it has real sections, so the
    /// surplus rows read as zeros instead of as arena bytes.
    row_gap: usize,
    trailing: usize,
}

impl Default for Builder {
    fn default() -> Self {
        Self {
            file_type: FileType::MODEL,
            object_count: 1,
            rows: Vec::new(),
            section_count: None,
            manifest_tc: MANIFEST_TC,
            types_tc: TYPES_TC,
            types_gap: 0,
            n_types: None,
            extra_type_codes: Vec::new(),
            buffer_pointer: None,
            buffer_size: None,
            section_info_pointer: None,
            manifest_o1: None,
            row_gap: 0,
            trailing: 0,
        }
    }
}

impl Builder {
    /// A valid two-section record: one BaseResource (so the address adjustment
    /// is exercised) and one Raster (so it is not).
    fn two_section() -> Self {
        Self::default()
            .row(RowSpec::new(BASE_RESOURCE_TC, vec![0x11; 12]))
            .row(RowSpec::new(0x20003, vec![0x22; 8]))
    }

    fn row(mut self, r: RowSpec) -> Self {
        self.rows.push(r);
        self
    }

    fn with_types_gap(mut self, gap: usize) -> Self {
        self.types_gap = gap;
        self
    }

    fn with_trailing(mut self, trailing: usize) -> Self {
        self.trailing = trailing;
        self
    }

    fn with_row_gap(mut self, gap: usize) -> Self {
        self.row_gap = gap;
        self
    }

    fn with_section_count(mut self, count: u32) -> Self {
        self.section_count = Some(count);
        self
    }

    fn with_buffer(mut self, pointer: u32, size: u32) -> Self {
        self.buffer_pointer = Some(pointer);
        self.buffer_size = Some(size);
        self
    }

    fn build(&self) -> Vec<u8> {
        let manifest_off = MANIFEST_OFFSET;
        let types_off = manifest_off + MANIFEST_SIZE + self.types_gap;

        // One entry per distinct section type code, first-seen order — exactly
        // what the committed fixture does.
        let mut type_codes: Vec<u32> = Vec::new();
        for r in &self.rows {
            if !type_codes.contains(&r.tc) {
                type_codes.push(r.tc);
            }
        }
        for t in &self.extra_type_codes {
            if !type_codes.contains(t) {
                type_codes.push(*t);
            }
        }

        let rows_off = types_off + 8 + 4 * type_codes.len();
        let arena_off = rows_off + SECTION_ROW_SIZE * self.rows.len() + self.row_gap;

        let mut payload: Vec<u8> = Vec::new();
        let mut payload_offsets: Vec<usize> = Vec::new();
        for r in &self.rows {
            payload_offsets.push(payload.len());
            payload.extend_from_slice(&r.payload);
        }

        let buffer_pointer = self.buffer_pointer.unwrap_or(arena_off as u32);
        let buffer_size = self.buffer_size.unwrap_or(payload.len() as u32);
        let record_len = arena_off + payload.len() + self.trailing;
        let mut out = vec![0u8; record_len];

        out[..MAGIC.len()].copy_from_slice(&MAGIC);
        put_u32(&mut out, FILE_TYPE_OFFSET, self.file_type);
        put_u32(&mut out, OBJECT_COUNT_OFFSET, self.object_count);
        put_u32(
            &mut out,
            SECTION_COUNT_OFFSET,
            self.section_count.unwrap_or(self.rows.len() as u32),
        );
        put_u32(
            &mut out,
            SECTION_INFO_POINTER_OFFSET,
            self.section_info_pointer.unwrap_or(rows_off as u32),
        );
        put_u32(&mut out, BUFFER_POINTER_OFFSET, buffer_pointer);
        put_u32(&mut out, BUFFER_SIZE_OFFSET, buffer_size);

        // Manifest. o1 defaults to the manifest-RELATIVE distance to the types
        // block, i.e. types_off - 0x98.
        put_u32(&mut out, manifest_off, self.manifest_tc);
        put_u32(
            &mut out,
            manifest_off + MANIFEST_TYPES_OFFSET_OFFSET,
            self.manifest_o1
                .unwrap_or((types_off - manifest_off) as u32),
        );

        // SectionTypes.
        put_u32(&mut out, types_off, self.types_tc);
        put_u32(
            &mut out,
            types_off + 4,
            self.n_types.unwrap_or(type_codes.len() as u32),
        );
        for (i, tc) in type_codes.iter().enumerate() {
            put_u32(&mut out, types_off + 8 + 4 * i, *tc);
        }

        // Rows.
        for (i, r) in self.rows.iter().enumerate() {
            let row = rows_off + SECTION_ROW_SIZE * i;
            // BaseResource pointers are arena-relative; everything else is
            // absolute. Emitting them correctly here is what makes the parsed
            // `data_address` a real test of the adjustment rule.
            let derived = if r.tc == BASE_RESOURCE_TC {
                payload_offsets[i] as u32
            } else {
                (arena_off + payload_offsets[i]) as u32
            };
            let tc_index = r.tc_index.unwrap_or_else(|| {
                type_codes
                    .iter()
                    .position(|t| *t == r.tc)
                    .map_or(-1, |p| p as i32)
            });
            put_u32(&mut out, row, r.data_pointer.unwrap_or(derived));
            put_u32(&mut out, row + 0x04, r.unknown_04);
            put_i32(
                &mut out,
                row + 0x08,
                r.size.unwrap_or(r.payload.len() as i32),
            );
            put_i32(&mut out, row + 0x0C, r.align);
            put_i32(&mut out, row + 0x10, tc_index);
            put_u32(&mut out, row + 0x14, r.tc);
        }

        out[arena_off..arena_off + payload.len()].copy_from_slice(&payload);
        out
    }
}

// ================================================================ constants

#[test]
fn magic_is_the_documented_28_bytes() {
    assert_eq!(MAGIC.len(), 28);
    assert_eq!(MAGIC_LEN, 28);
    // Bytes 12..15 are the trap: Rw4.hpp's ASCII comment renders them as
    // 0x20 0x34 0x00 (" 4\0"), which is wrong. The array is authoritative.
    assert_eq!(&MAGIC[12..16], &[0x00, 0x20, 0x04, 0x00]);
    // Full literal, so drift in the middle is caught too.
    assert_eq!(
        MAGIC,
        [
            0x89, 0x52, 0x57, 0x34, 0x77, 0x33, 0x32, 0x00, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x20,
            0x04, 0x00, 0x34, 0x35, 0x34, 0x00, 0x30, 0x30, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00,
        ]
    );
}

#[test]
fn rw4_type_is_the_spore_rw4_record_type() {
    assert_eq!(RW4_TYPE, 0x2F4E_681B);
    assert_eq!(RW4_TYPE, spore_core::record::type_id::RW4);
}

#[test]
fn layout_constants_match_the_documented_offsets() {
    assert_eq!(MIN_RECORD_SIZE, 0x98 + 0x1C);
    assert_eq!(MIN_RECORD_SIZE, 180);
    assert_eq!(MANIFEST_OFFSET, 0x98);
    assert_eq!(MANIFEST_SIZE, 0x1C);
    assert_eq!(SECTION_ROW_SIZE, 24);
    assert_eq!(MANIFEST_TYPES_OFFSET_OFFSET, 0x0C);
    assert_eq!(MANIFEST_TC, 0x10004);
    assert_eq!(TYPES_TC, 0x10005);
    assert_eq!(BASE_RESOURCE_TC, 0x10030);
    assert_eq!(FILE_TYPE_OFFSET, 0x1C);
    assert_eq!(OBJECT_COUNT_OFFSET, 0x20);
    assert_eq!(SECTION_COUNT_OFFSET, 0x24);
    assert_eq!(SECTION_INFO_POINTER_OFFSET, 0x30);
    assert_eq!(BUFFER_POINTER_OFFSET, 0x44);
    assert_eq!(BUFFER_SIZE_OFFSET, 0x4C);
}

#[test]
fn file_type_classification_is_total_and_exact() {
    assert_eq!(FileType::from_raw(1), FileType::Model);
    assert_eq!(FileType::from_raw(0x0400_0000), FileType::Texture);
    assert_eq!(FileType::from_raw(0xCAFE_D00D), FileType::Special);
    assert_eq!(FileType::from_raw(2), FileType::Unknown(2));
    assert_eq!(FileType::Unknown(0xDEAD_BEEF).raw(), 0xDEAD_BEEF);
    assert_eq!(FileType::from_raw(0xCAFE_D00D).raw(), 0xCAFE_D00D);
    assert!(FileType::from_raw(1).is_known());
    assert!(!FileType::from_raw(0).is_known());
    assert_eq!(FileType::Model.to_string(), "MODEL");
    assert_eq!(FileType::Special.to_string(), "SPECIAL");
    assert_eq!(FileType::Unknown(0x1234_5678).to_string(), "0x12345678");
}

// ================================================================ fixture

#[test]
fn parses_committed_fixture_every_field() {
    let r = fixture();

    // Header.
    assert_eq!(r.file_type, 1);
    assert_eq!(r.file_type_enum(), FileType::Model);
    assert_eq!(r.object_count, 1);
    assert_eq!(r.section_count, 3);
    assert_eq!(r.section_info_pointer, 0x0F0);
    assert_eq!(r.buffer_pointer, 0x138);
    assert_eq!(r.buffer_size, 0x188 - 0x138);
    assert_eq!(r.buffer_size, 0x50);
    assert_eq!(r.buffer_size, 80);
    assert_eq!(r.record_size, FIXTURE.len());
    assert_eq!(r.record_size, 392);
    // gen_fixtures.py writes no words at 0x28/0x2C/0x34/0x48, so they stay zero.
    assert_eq!(r.unknown_28, 0);
    assert_eq!(r.unknown_2c, 0);
    assert_eq!(r.unknown_34, 0);
    assert_eq!(r.unknown_48, 0);

    // SectionTypes block at 0x98 + o1 where o1 == 0x1C.
    assert_eq!(r.type_codes, vec![0x10030, 0x20003, 0x40001]);
}

#[test]
fn fixture_sections_match_the_generated_rows() {
    let r = fixture();
    assert_eq!(r.sections.len(), 3);

    let base = r.sections[0];
    assert_eq!(base.row_offset, 0x0F0);
    assert_eq!(base.data_pointer, 0);
    assert_eq!(base.unknown_04, 0);
    assert_eq!(base.size, 12);
    assert_eq!(base.align, 1);
    assert_eq!(base.type_code_index, 0);
    assert_eq!(base.type_code, 0x10030);

    let raster = r.sections[1];
    assert_eq!(raster.row_offset, 0x0F0 + 24);
    assert_eq!(raster.data_pointer, 0x144);
    assert_eq!(raster.unknown_04, 0);
    assert_eq!(raster.size, 44);
    assert_eq!(raster.align, 1);
    assert_eq!(raster.type_code_index, 1);
    assert_eq!(raster.type_code, 0x20003);

    let mesh = r.sections[2];
    assert_eq!(mesh.row_offset, 0x0F0 + 48);
    assert_eq!(mesh.data_pointer, 0x170);
    assert_eq!(mesh.unknown_04, 0);
    assert_eq!(mesh.size, 24);
    assert_eq!(mesh.align, 1);
    assert_eq!(mesh.type_code_index, 2);
    assert_eq!(mesh.type_code, 0x40001);
}

#[test]
fn fixture_base_resource_address_is_adjusted_and_the_others_are_not() {
    let r = fixture();

    // THE RULE: only 0x10030 adds the arena base.
    let base = r.sections[0];
    assert_eq!(base.type_code, BASE_RESOURCE_TC);
    assert_eq!(base.data_address, base.data_pointer + r.buffer_pointer);
    assert_eq!(base.data_address, 0x138);
    assert_eq!(base.data_address, 0x138);

    // The other two store absolute pointers and are left untouched.
    for s in &r.sections[1..] {
        assert_ne!(s.type_code, BASE_RESOURCE_TC);
        assert_eq!(s.data_address, s.data_pointer);
    }
    assert_eq!(r.sections[1].data_address, 0x144);
    assert_eq!(r.sections[2].data_address, 0x170);

    // Each section's payload lands exactly where the arena says it should,
    // which is the only reason the adjustment is worth doing.
    assert_eq!(r.sections[0].end_address(), Some(0x138 + 12));
    assert_eq!(r.sections[1].end_address(), Some(0x144 + 44));
    assert_eq!(r.sections[2].end_address(), Some(0x170 + 24));
    for s in &r.sections {
        let end = s.end_address().expect("fixture sizes are non-negative");
        assert!(end <= r.record_size as u64);
        assert!(end as usize <= FIXTURE.len());
    }
}

#[test]
fn describe_matches_the_python_oracle_byte_for_byte() {
    // Produced by:
    //   python3 tools/spore/rw4/rw4.py tests/fixtures/mini_rw4.rw4
    // whose describe() line is byte-identical to the C++ Rw4::describe().
    let line = fixture().describe();
    assert_eq!(line, FIXTURE_DESCRIBE);
    // Spot-check the format rules themselves so a change to any one of them is
    // attributable: 0x prefix on ftype/data_address, none on type_code, all
    // lowercase, no zero padding, decimal counts.
    assert!(line.starts_with("0x1 obj=1 sec=3 buf=80 | "), "{line}");
    assert!(line.contains(" | 10030 d=0x138 s=12 | "), "{line}");
    assert!(!line.contains("0x00000001"), "no zero padding: {line}");
    assert!(!line.contains("0X"), "lowercase hex only: {line}");
}

#[test]
fn describe_of_a_header_only_record_matches_the_oracle_shape() {
    // Same format the oracle emits for a zero-section record: the loop simply
    // contributes nothing. Proves describe() is not fixture-shaped.
    let b = Builder::default().build();
    let r = parse(&b).expect("header-only record parses");
    assert_eq!(r.sections.len(), 0);
    assert_eq!(r.describe(), "0x1 obj=1 sec=0 buf=0");
}

#[test]
fn fixture_is_complete() {
    let r = fixture();
    assert_eq!(r.sections.len(), r.section_count as usize);
    assert!(r.sections.iter().all(|s| s.size >= 0));
    assert!(r
        .sections
        .iter()
        .all(|s| s.end_address().is_some_and(|e| e <= r.record_size as u64)));
    assert!(r.is_complete());
}

#[test]
fn fixture_unknown_type_codes_counts_0x40001() {
    let r = fixture();
    // 0x10030 and 0x20003 are in the C++ set. 0x40001 is NOT: the C++ names Mesh
    // at 0x20009 and the Python oracle names Mesh at 0x40001. The committed
    // fixture therefore carries exactly one code the C++ walker counts as
    // undocumented.
    //
    // The task brief predicted 0 here; the reference disagrees. Verified by
    // compiling src/assets/Rw4.cpp and running it over the fixture:
    //   unknown=1 ... [2] pData=0x170 size=24 align=1 tcIdx=2 tc=0x40001
    //   data=0x170 known=0
    // Adding 0x40001 to the C++ set to force a 0 would change the reference's
    // semantics, not fix a defect here.
    assert!(!known_type_code(0x40001));
    assert!(known_type_code(0x10030));
    assert!(known_type_code(0x20003));
    assert_eq!(r.unknown_type_codes(), 1);
    assert!(!r.sections[0].has_unknown_type_code());
    assert!(!r.sections[1].has_unknown_type_code());
    assert!(r.sections[2].has_unknown_type_code());
}

// ================================================================ type tables

#[test]
fn cpp_table_membership_for_known_ids() {
    for tc in [
        0x10030, 0x10004, 0x10005, 0x10006, 0x10007, 0x10008, 0x20003, 0x20007, 0x20008, 0x20009,
        0x2000b, 0x2001a, 0x200af, 0x70001, 0x70002, 0x70003, 0x7000b, 0x80003, 0x80005, 0xff0000,
        0xff0001, 0xff0002,
    ] {
        assert!(known_type_code(tc), "{tc:#x} must be in the C++ set");
    }
    assert_eq!(CPP_TYPE_CODES.len(), 22);
    // The exported list and the predicate must not drift apart.
    for tc in CPP_TYPE_CODES {
        assert!(known_type_code(*tc), "CPP_TYPE_CODES lists {tc:#x}");
    }
}

#[test]
fn cpp_table_rejects_spore_only_and_adjacent_codes() {
    // Spore emits these two; they are in NEITHER reference table. Measured over
    // the 1,131 real records: 591 sections each.
    for tc in SPORE_ONLY_TYPE_CODES {
        assert!(!known_type_code(*tc), "{tc:#x} is Spore-only");
        assert_eq!(python_type_name(*tc), None, "{tc:#x} is Spore-only");
        assert_eq!(cpp_type_name(*tc), None, "{tc:#x} is Spore-only");
    }
    assert_eq!(SPORE_ONLY_TYPE_CODES, &[0x7000c, 0x7000f]);
    // Codes that are genuinely unknown to BOTH references.
    for tc in [0x0000_0000u32, 0x10009, 0x70004, 0xffff_ffff, 0xDEAD_BEEF] {
        assert!(!known_type_code(tc), "{tc:#x} is not a known code");
        assert_eq!(python_type_name(tc), None, "{tc:#x} is not in TYPES");
    }
    // A code the oracle knows and the C++ set does not — 0x20002 is
    // VertexBuffer in TYPES and absent from inKnownSet. Recorded here because
    // it is exactly the kind of id that gets "helpfully" added to the C++ set.
    assert!(!known_type_code(0x20002));
    assert_eq!(python_type_name(0x20002), Some("VertexBuffer"));
}

#[test]
fn cpp_table_names_cover_the_set_except_the_two_unmapped_codes() {
    let named = CPP_TYPE_CODES
        .iter()
        .filter(|tc| cpp_type_name(**tc).is_some())
        .count();
    assert_eq!(named, CPP_TYPE_CODES.len() - CPP_UNNAMED_TYPE_CODES.len());
    assert_eq!(CPP_UNNAMED_TYPE_CODES, &[0x2000b, 0x7000b]);
    // In the set, deliberately unnamed — no name is invented for them.
    assert!(known_type_code(0x2000b));
    assert_eq!(cpp_type_name(0x2000b), None);
    assert!(known_type_code(0x7000b));
    assert_eq!(cpp_type_name(0x7000b), None);
    // A named member, to prove the filter above is not vacuous.
    assert_eq!(cpp_type_name(0x10030), Some("BaseResource"));
    assert_eq!(fixture().type_code_name(0x10030), Some("BaseResource"));
    assert_eq!(fixture().type_code_name(0x40001), None);
}

#[test]
fn python_table_is_exposed_verbatim() {
    assert_eq!(PYTHON_TYPE_CODES.len(), 29);
    for tc in PYTHON_TYPE_CODES {
        assert!(python_type_name(*tc).is_some(), "{tc:#x} must be in TYPES");
    }
    // The oracle's own placeholder is reproduced, not replaced with a guess.
    assert_eq!(python_type_name(0x10010), Some("?"));
    assert_eq!(python_type_name(0x10031), Some("?"));
    assert_eq!(python_type_name(0x10032), Some("?"));
    assert_eq!(python_type_name(0x40001), Some("Mesh"));
    assert_eq!(python_type_name(0xc0001), Some("TextureOverride"));
    assert_eq!(python_type_name(0x80003), Some("BBox"));
    assert_eq!(python_type_name(0x70001), Some("SkinsInK"));
}

#[test]
fn the_two_reference_tables_disagree_and_stay_that_way() {
    // Pinned deliberately. If someone "unifies" these two functions, this test
    // is the thing that tells them which corpus they broke.

    // Same id, DIFFERENT name. Two ids do this.
    assert_eq!(cpp_type_name(0x70001), Some("KeyframeAnim"));
    assert_eq!(python_type_name(0x70001), Some("SkinsInK"));
    assert_eq!(cpp_type_name(0x80003), Some("TriangleKDTreeProcedural"));
    assert_eq!(python_type_name(0x80003), Some("BBox"));

    // Same name, DIFFERENT id.
    assert_eq!(cpp_type_name(0x20009), Some("Mesh"));
    assert_eq!(python_type_name(0x20009), None);
    assert_eq!(python_type_name(0x40001), Some("Mesh"));
    assert_eq!(cpp_type_name(0x40001), None);
    assert_eq!(cpp_type_name(0x70003), Some("AnimationSkin"));
    assert_eq!(python_type_name(0x70003), None);
    assert_eq!(python_type_name(0x30001), Some("AnimationSkin"));

    // Membership differs, not just spelling.
    assert!(known_type_code(0x20009) && !known_type_code(0x40001));
    assert!(known_type_code(0x70002) && !known_type_code(0x80002));
    assert!(!known_type_code(0x20001) && python_type_name(0x20001).is_some());
    assert!(!known_type_code(0x20004) && python_type_name(0x20004).is_some());

    // Set arithmetic: they share 9 ids, and neither contains the other.
    let cpp: std::collections::BTreeSet<u32> = CPP_TYPE_CODES.iter().copied().collect();
    let py: std::collections::BTreeSet<u32> = PYTHON_TYPE_CODES.iter().copied().collect();
    assert_eq!(cpp.len(), 22);
    assert_eq!(py.len(), 29);
    let shared: Vec<u32> = cpp.intersection(&py).copied().collect();
    assert_eq!(
        shared,
        vec![0x10004, 0x10005, 0x10006, 0x10007, 0x10008, 0x10030, 0x20003, 0x70001, 0x80003]
    );
    assert_eq!(cpp.difference(&py).count(), 13);
    assert_eq!(py.difference(&cpp).count(), 20);
    assert_ne!(cpp, py);
}

// ================================================================ negatives

#[test]
fn rejects_bad_magic() {
    let mut b = FIXTURE.to_vec();
    b[7] ^= 0x01;
    assert_eq!(
        parse(&b),
        Err(Rw4Error::BadMagic {
            offset: 7,
            found: 0x01,
            want: 0x00,
        })
    );
    // Flipping a byte in the trap region (12..16) is caught the same way.
    let mut c = FIXTURE.to_vec();
    c[14] = 0xFF;
    assert!(matches!(
        parse(&c),
        Err(Rw4Error::BadMagic {
            offset: 14,
            found: 0xFF,
            ..
        })
    ));
}

#[test]
fn rejects_too_short_record() {
    assert_eq!(
        parse(&[]),
        Err(Rw4Error::TooShort {
            len: 0,
            needed: MIN_RECORD_SIZE
        })
    );
    let short = &FIXTURE[..MIN_RECORD_SIZE - 1];
    assert_eq!(
        parse(short),
        Err(Rw4Error::TooShort {
            len: short.len(),
            needed: MIN_RECORD_SIZE
        })
    );
    // One byte more and the length check is satisfied, so a DIFFERENT error
    // comes back: the boundary is exactly where the constant claims.
    assert!(!matches!(
        parse(&FIXTURE[..MIN_RECORD_SIZE]),
        Err(Rw4Error::TooShort { .. })
    ));
}

#[test]
fn minimum_length_record_reaches_the_manifest_check() {
    // A MIN_RECORD_SIZE buffer with a valid header and no manifest content:
    // the length gate lets it through and the manifest type code is what fails.
    // This is why there is no separate "too small for manifest" variant — the
    // C++ has one, and here it is provably unreachable.
    let mut b = vec![0u8; MIN_RECORD_SIZE];
    b[..MAGIC.len()].copy_from_slice(&MAGIC);
    put_u32(&mut b, FILE_TYPE_OFFSET, FileType::MODEL);
    assert_eq!(parse(&b), Err(Rw4Error::ManifestTypeCode { found: 0 }));
    // Put the manifest type code right and the *next* defect surfaces: o1 == 0
    // puts the SectionTypes block back at 0x98, where the type code is the
    // manifest's own 0x10004.
    put_u32(&mut b, MANIFEST_OFFSET, MANIFEST_TC);
    assert_eq!(
        parse(&b),
        Err(Rw4Error::SectionTypesTypeCode { found: 0x10004 })
    );
}

#[test]
fn rejects_bad_file_type() {
    let mut b = Builder::default().build();
    put_u32(&mut b, FILE_TYPE_OFFSET, 0x1234_5678);
    assert_eq!(
        parse(&b),
        Err(Rw4Error::BadFileType {
            file_type: 0x1234_5678
        })
    );
    // 0 is the tempting near-miss: it is not one of the three.
    let mut c = Builder::default().build();
    put_u32(&mut c, FILE_TYPE_OFFSET, 0);
    assert_eq!(parse(&c), Err(Rw4Error::BadFileType { file_type: 0 }));
}

#[test]
fn accepts_every_known_file_type() {
    for raw in [FileType::MODEL, FileType::TEXTURE, FileType::SPECIAL] {
        let mut b = Builder::default().build();
        put_u32(&mut b, FILE_TYPE_OFFSET, raw);
        let r = parse(&b).expect("known file type parses");
        assert_eq!(r.file_type, raw);
        assert_eq!(r.file_type_enum(), FileType::from_raw(raw));
        assert!(r.describe().starts_with(&format!("0x{raw:x} obj=1")));
    }
}

#[test]
fn rejects_manifest_type_code_mismatch() {
    let mut b = Builder::default().build();
    put_u32(&mut b, MANIFEST_OFFSET, 0x10005);
    assert_eq!(
        parse(&b),
        Err(Rw4Error::ManifestTypeCode { found: 0x10005 })
    );
    let mut c = Builder::default().build();
    put_u32(&mut c, MANIFEST_OFFSET, 0);
    assert_eq!(parse(&c), Err(Rw4Error::ManifestTypeCode { found: 0 }));
}

#[test]
fn rejects_section_types_type_code_mismatch() {
    let mut b = Builder::default().build();
    // types_off == 0x98 + 0x1C == 0xB4 for the default builder.
    assert_eq!(read_u32(&b, 0xA4), 0x1C);
    put_u32(&mut b, 0xB4, MANIFEST_TC);
    assert_eq!(
        parse(&b),
        Err(Rw4Error::SectionTypesTypeCode { found: 0x10004 })
    );
}

#[test]
fn rejects_section_info_pointer_out_of_range() {
    let mut b = Builder::default().build();
    let beyond = b.len() as u32 + 0x100;
    put_u32(&mut b, SECTION_INFO_POINTER_OFFSET, beyond);
    assert_eq!(
        parse(&b),
        Err(Rw4Error::SectionInfoPointerOutOfRange {
            ptr: beyond,
            len: b.len()
        })
    );
    // u32::MAX is the strongest form of the same fact.
    let mut c = Builder::default().build();
    put_u32(&mut c, SECTION_INFO_POINTER_OFFSET, u32::MAX);
    assert!(matches!(
        parse(&c),
        Err(Rw4Error::SectionInfoPointerOutOfRange { ptr: u32::MAX, .. })
    ));
}

#[test]
fn rejects_section_table_overrunning_the_record() {
    // The pointer is valid; the COUNT is not. That is the whole reason this is
    // kept separate from SectionInfoPointerOutOfRange.
    let mut b = Builder::two_section().build();
    let ptr = read_u32(&b, SECTION_INFO_POINTER_OFFSET);
    put_u32(&mut b, SECTION_COUNT_OFFSET, 0x1_0000);
    let len = b.len();
    match parse(&b).expect_err("a count that overruns must be refused") {
        Rw4Error::SectionTableOverrunsRecord {
            count,
            ptr: got,
            needed,
            avail,
        } => {
            assert_eq!(count, 0x1_0000);
            assert_eq!(got, ptr);
            assert_eq!(needed, 0x1_0000 * 24);
            assert_eq!(avail, len as u64 - ptr as u64);
            assert!(needed > avail);
        }
        other => panic!("wrong variant: {other}"),
    }
}

#[test]
fn rejects_manifest_relative_offset_out_of_range() {
    let mut b = Builder::default().build();
    put_u32(
        &mut b,
        MANIFEST_OFFSET + MANIFEST_TYPES_OFFSET_OFFSET,
        0xFFFF_FF00,
    );
    let len = b.len();
    assert_eq!(
        parse(&b),
        Err(Rw4Error::ManifestRelativeOffsetOutOfRange {
            offset: 0xFFFF_FF00,
            absolute: 0x98 + 0xFFFF_FF00u64,
            len,
        })
    );
    // The absolute value in the message is 0x98 + o1, never o1 — the whole
    // point of the variant is that the offset is manifest-relative.
    let mut c = Builder::default().build();
    put_u32(
        &mut c,
        MANIFEST_OFFSET + MANIFEST_TYPES_OFFSET_OFFSET,
        len as u32,
    );
    let l2 = c.len();
    assert!(matches!(
        parse(&c),
        Err(Rw4Error::ManifestRelativeOffsetOutOfRange { absolute, .. })
            if absolute == 0x98 + l2 as u64
    ));
}

#[test]
fn rejects_types_block_out_of_range() {
    // The 8-byte header fits; the declared count does not.
    let mut b = Builder::two_section().build();
    assert_eq!(read_u32(&b, 0xA4), 0x1C);
    put_u32(&mut b, 0xB4 + 4, 0x1_0000);
    let len = b.len();
    match parse(&b).expect_err("an oversized type table must be refused") {
        Rw4Error::TypesBlockOutOfRange {
            count,
            base,
            needed,
            avail,
        } => {
            assert_eq!(count, 0x1_0000);
            assert_eq!(base, 0xB4);
            assert_eq!(needed, 0xB4 + 8 + 0x1_0000 * 4);
            assert_eq!(avail, len as u64 - 0xB4);
            assert!(needed > avail);
        }
        other => panic!("wrong variant: {other}"),
    }
}

#[test]
fn rejects_arena_bounds_violation() {
    // base past the end
    let mut a = Builder::default().build();
    let beyond = a.len() as u32 + 0x40;
    put_u32(&mut a, BUFFER_POINTER_OFFSET, beyond);
    assert!(matches!(
        parse(&a),
        Err(Rw4Error::ArenaBoundsViolation { base, .. }) if base == beyond
    ));
    // base fine, size past the end
    let mut b = Builder::default().build();
    put_u32(&mut b, BUFFER_SIZE_OFFSET, u32::MAX);
    assert!(matches!(
        parse(&b),
        Err(Rw4Error::ArenaBoundsViolation { size, .. }) if size == u32::MAX
    ));
    // base == len and size == 0 is the tightest legal arena and must NOT fire.
    let mut c = Builder::default().build();
    let len = c.len() as u32;
    put_u32(&mut c, BUFFER_POINTER_OFFSET, len);
    put_u32(&mut c, BUFFER_SIZE_OFFSET, 0);
    assert!(parse(&c).is_ok());
}

#[test]
fn rejects_address_adjustment_overflow() {
    // BaseResource with data_pointer 0xFFFF_FFF0 and an arena base of 0x100:
    // 0xFFFF_FFF0 + 0x100 == 0x1_0000_000F, past u32::MAX. The arena check
    // passes first (base <= len, size <= len - base), so the overflow is the
    // only defect present.
    let mut spec = RowSpec::new(BASE_RESOURCE_TC, vec![0u8; 4]);
    spec.data_pointer = Some(0xFFFF_FFF0);
    let b2 = Builder::default()
        .row(spec)
        .with_buffer(0x100, 0)
        .with_trailing(0x200)
        .build();
    assert!(b2.len() >= 0x100, "record must cover the arena base");
    assert_eq!(
        parse(&b2),
        Err(Rw4Error::AddressAdjustmentOverflow {
            index: 0,
            data_pointer: 0xFFFF_FFF0,
            buffer_pointer: 0x100,
        })
    );

    // The same data_pointer on a NON-BaseResource row cannot overflow: nothing
    // is added to it.
    let bytes = Builder::default()
        .row(RowSpec::new(0x20003, vec![0u8; 4]))
        .with_buffer(0x100, 0)
        .with_trailing(0x200)
        .build();
    let ptr = read_u32(&bytes, SECTION_INFO_POINTER_OFFSET) as usize;
    let mut c = bytes;
    put_u32(&mut c, ptr, 0xFFFF_FFF0);
    let r = parse(&c).expect("no adjustment, no overflow");
    assert_eq!(r.sections[0].data_address, 0xFFFF_FFF0);
    assert!(!r.is_complete(), "and the directory is simply incomplete");
}

#[test]
fn rejects_bad_section_type_code_index() {
    // Index past the end of the record's own type table.
    let mut spec = RowSpec::new(0x20003, vec![0u8; 4]);
    spec.tc_index = Some(7);
    assert_eq!(
        parse(&Builder::default().row(spec).build()),
        Err(Rw4Error::BadSectionTypeCodeIndex {
            index: 0,
            index_value: 7,
            count: 1,
        })
    );
    // Negative index: the field is signed, so -1 is expressible.
    let mut neg = RowSpec::new(0x20003, vec![0u8; 4]);
    neg.tc_index = Some(-1);
    assert_eq!(
        parse(&Builder::default().row(neg).build()),
        Err(Rw4Error::BadSectionTypeCodeIndex {
            index: 0,
            index_value: -1,
            count: 1,
        })
    );
    // The last row is the one that fails, and it reports its own index.
    let mut last = RowSpec::new(0x20003, vec![0u8; 4]);
    last.tc_index = Some(2);
    let b = Builder::two_section().row(last).build();
    assert_eq!(
        parse(&b),
        Err(Rw4Error::BadSectionTypeCodeIndex {
            index: 2,
            index_value: 2,
            count: 2,
        })
    );
}

// ================================================================ builder

#[test]
fn builder_emits_a_record_the_parser_round_trips() {
    let b = Builder::two_section().build();
    assert!(b.len() >= MIN_RECORD_SIZE);
    let r = parse(&b).expect("builder output parses");
    assert_eq!(r.file_type, 1);
    assert_eq!(r.object_count, 1);
    assert_eq!(r.section_count, 2);
    assert_eq!(r.type_codes, vec![BASE_RESOURCE_TC, 0x20003]);
    assert_eq!(r.sections.len(), 2);
    assert!(r.is_complete());
    assert_eq!(r.unknown_type_codes(), 0);

    // Forward proof of the address rule: the BaseResource row stores an
    // arena-relative 0 and still resolves inside the arena.
    let arena_off = r.buffer_pointer;
    assert_eq!(r.sections[0].data_pointer, 0);
    assert_eq!(r.sections[0].data_address, arena_off);
    assert_eq!(r.sections[1].data_pointer, arena_off + 12);
    assert_eq!(r.sections[1].data_address, arena_off + 12);
    assert_eq!(r.sections[0].size, 12);
    assert_eq!(r.sections[1].size, 8);
}

#[test]
fn builder_zero_gap_produces_the_corpus_style_o1() {
    let bytes = Builder::two_section().build();
    // o1 == 0x1C, which is what all 1,131 real records carry.
    assert_eq!(
        read_u32(&bytes, MANIFEST_OFFSET + MANIFEST_TYPES_OFFSET_OFFSET),
        MANIFEST_SIZE as u32
    );
}

#[test]
fn builder_non_zero_manifest_relative_offset_is_required() {
    // If parse() forgot to add 0x98 to o1 it would look for the types block at
    // o1 == 0x2C, read zeros, and report SectionTypesTypeCode { found: 0 }.
    let bytes = Builder::two_section().with_types_gap(0x10).build();
    assert_eq!(
        read_u32(&bytes, MANIFEST_OFFSET + MANIFEST_TYPES_OFFSET_OFFSET),
        0x2C
    );
    // The block really is at 0x98 + 0x2C == 0xC4, and nowhere near 0x2C.
    assert_eq!(read_u32(&bytes, 0x2C), 0);
    assert_eq!(read_u32(&bytes, 0xC4), TYPES_TC);
    let r = parse(&bytes).expect("non-zero o1 parses");
    assert_eq!(r.type_codes, vec![BASE_RESOURCE_TC, 0x20003]);
    assert_eq!(r.sections.len(), 2);
    assert!(r.is_complete());
}

#[test]
fn unknown_type_code_parses_and_is_only_counted() {
    // THE INVARIANT: an unknown type code is not a structural failure. Refusing
    // it would refuse the 1,182 such sections in the real corpus.
    let mut builder = Builder::two_section();
    builder.rows[1].tc = 0x7000f; // Spore-specific, in neither table.
    let r = parse(&builder.build()).expect("unknown type code must still parse");
    assert_eq!(r.sections.len(), 2);
    assert_eq!(r.sections[1].type_code, 0x7000f);
    assert!(r.sections[1].has_unknown_type_code());
    assert_eq!(r.unknown_type_codes(), 1);
    assert!(r.is_complete(), "unknown code does not affect completeness");
    // It still appears in the directory verbatim — not renamed, not dropped.
    assert!(r.describe().contains(" | 7000f d="), "{}", r.describe());
}

#[test]
fn section_count_larger_than_the_rows_present_is_refused() {
    let bytes = Builder::two_section().with_section_count(7).build();
    match parse(&bytes).expect_err("a count with no rows must be refused") {
        Rw4Error::SectionTableOverrunsRecord { count, .. } => assert_eq!(count, 7),
        other => panic!("wrong variant: {other}"),
    }
}

#[test]
fn extra_zero_rows_are_read_as_zero_filled_sections() {
    // The other half of the same story: when the record physically carries the
    // extra rows, parse succeeds and they read as type code 0 — unknown, counted,
    // and (being size 0 at address 0) trivially in bounds. `row_gap` puts a zero
    // region where the surplus rows are read from, so they really are zeros
    // rather than arena bytes.
    let bytes = Builder::two_section()
        .with_section_count(5)
        .with_row_gap(3 * SECTION_ROW_SIZE)
        .build();
    let r = parse(&bytes).expect("the extra rows are physically present");
    assert_eq!(r.section_count, 5);
    assert_eq!(r.sections.len(), 5);
    for s in &r.sections[2..] {
        assert_eq!(s.type_code, 0);
        assert_eq!(s.size, 0);
        assert_eq!(s.data_address, 0);
        assert_eq!(s.type_code_index, 0);
        assert_eq!(s.unknown_04, 0);
        assert_eq!(s.align, 0);
    }
    assert_eq!(r.unknown_type_codes(), 3);
    assert!(
        r.is_complete(),
        "zero rows at address 0 are trivially in bounds"
    );
}

// ================================================================ property

#[test]
fn a_section_past_the_record_end_is_incomplete_not_an_error() {
    // Completeness is a PROPERTY. The C++ refuses this record outright; this
    // crate hands over the directory and lets the caller decide.
    let mut spec = RowSpec::new(0x20003, vec![0x33; 8]);
    spec.data_pointer = Some(0x1000);
    let bytes = Builder::default().row(spec).with_buffer(0x20, 8).build();
    let r = parse(&bytes).expect("an over-long section is still parseable");
    assert_eq!(r.sections[0].data_address, 0x1000);
    assert!(r.sections[0]
        .end_address()
        .is_some_and(|e| e > r.record_size as u64));
    assert!(!r.is_complete());
    assert_eq!(r.unknown_type_codes(), 0);
}

#[test]
fn a_negative_section_size_is_incomplete_not_an_error() {
    let mut spec = RowSpec::new(0x20003, vec![0x33; 8]);
    spec.size = Some(-8);
    let r = parse(&Builder::default().row(spec).build()).expect("parses");
    assert_eq!(r.sections[0].size, -8);
    assert_eq!(r.sections[0].end_address(), None);
    assert!(!r.is_complete());
    // describe() must print the size signed, exactly as the oracle's %d does.
    let line = r.describe();
    assert!(line.ends_with(" s=-8"), "{line}");
}

#[test]
fn is_complete_rejects_a_row_count_that_disagrees_with_the_header() {
    // After a successful parse `sections.len() == section_count` is a
    // tautology (both references have the same tautology), so this arm of
    // is_complete() is only reachable on a hand-built value. All fields are
    // public, so a caller assembling one is a supported thing to do.
    let mut r = fixture();
    assert!(r.is_complete());
    r.section_count = 4;
    assert!(!r.is_complete());
    r.section_count = 2;
    assert!(!r.is_complete());
}

#[test]
fn every_parsed_record_has_one_row_per_declared_section() {
    // The tautology above, checked empirically over the fixture and every
    // builder shape, so a future change to the row loop cannot quietly break it.
    let records = [
        Builder::default().build(),
        Builder::two_section().build(),
        Builder::two_section().with_types_gap(0x40).build(),
        Builder::two_section()
            .with_section_count(5)
            .with_row_gap(3 * SECTION_ROW_SIZE)
            .build(),
    ];
    for bytes in records {
        let r = parse(&bytes).expect("record parses");
        assert_eq!(r.sections.len(), r.section_count as usize);
    }
    let r = fixture();
    assert_eq!(r.sections.len(), r.section_count as usize);
}

// ================================================================ robustness

#[test]
fn truncation_sweep_never_panics() {
    let mut ok = 0usize;
    let mut err = 0usize;
    for n in 0..=FIXTURE.len() {
        match parse(&FIXTURE[..n]) {
            Ok(_) => ok += 1,
            Err(_) => err += 1,
        }
    }
    assert_eq!(ok + err, FIXTURE.len() + 1);
    // Only the full record satisfies every bound simultaneously.
    assert_eq!(ok, 1);
    assert_eq!(err, FIXTURE.len());
}

#[test]
fn truncation_sweep_with_valid_magic_walks_the_deeper_checks() {
    // Prefix safety alone is not enough: a truncated record whose magic has
    // been restored must be walked through the header checks, not just
    // length-rejected. Every mutation below keeps the buffer >= MIN_RECORD_SIZE
    // so the deep paths are actually reached.
    let mut walked = 0usize;
    for n in MIN_RECORD_SIZE..=FIXTURE.len() {
        let mut b = FIXTURE[..n].to_vec();
        b[..MAGIC.len()].copy_from_slice(&MAGIC);
        for byte in [0x7Fu32, 0xFFFF_FFFF, 0xFFFF_FF00, 0x8000_0000] {
            let mut c = b.clone();
            put_u32(&mut c, SECTION_COUNT_OFFSET, byte);
            put_u32(&mut c, BUFFER_POINTER_OFFSET, byte);
            put_u32(&mut c, BUFFER_SIZE_OFFSET, byte);
            put_u32(&mut c, SECTION_INFO_POINTER_OFFSET, byte);
            if let Some(slot) = c.get_mut(MANIFEST_OFFSET + MANIFEST_TYPES_OFFSET_OFFSET) {
                *slot = byte as u8;
            }
            if parse(&c).is_err() {
                walked += 1;
            }
        }
    }
    assert!(
        walked > 0,
        "the sweep must actually exercise the deep checks"
    );
}

#[test]
fn hostile_headers_never_panic() {
    // Every header word replaced with an extreme value, on a record long
    // enough to pass the length and magic checks. Each of these is a place a
    // naive parser multiplies, subtracts or indexes without checking.
    let base = Builder::two_section().build();
    let extremes = [0u32, 1, 0x7FFF_FFFF, 0x8000_0000, u32::MAX, 0xFFFF_FF00];
    for word in [
        FILE_TYPE_OFFSET,
        OBJECT_COUNT_OFFSET,
        SECTION_COUNT_OFFSET,
        SECTION_INFO_POINTER_OFFSET,
        0x28,
        0x2C,
        0x34,
        BUFFER_POINTER_OFFSET,
        0x48,
        BUFFER_SIZE_OFFSET,
        MANIFEST_OFFSET,
        MANIFEST_OFFSET + MANIFEST_TYPES_OFFSET_OFFSET,
    ] {
        for v in extremes {
            let mut b = base.clone();
            put_u32(&mut b, word, v);
            let _ = parse(&b);
            for n in [MIN_RECORD_SIZE, base.len() / 2, base.len()] {
                if n <= b.len() {
                    let _ = parse(&b[..n]);
                }
            }
        }
    }
}

#[test]
fn zeroed_and_ones_filled_records_fail_cleanly() {
    assert!(matches!(
        parse(&[0u8; 4096]),
        Err(Rw4Error::BadMagic { offset: 0, .. })
    ));
    assert!(matches!(
        parse(&[0xFFu8; 4096]),
        Err(Rw4Error::BadMagic { offset: 0, .. })
    ));
    // Valid magic and a known file type, then nothing: the manifest fails, not
    // an out-of-range read.
    let mut b = vec![0u8; MIN_RECORD_SIZE];
    b[..MAGIC.len()].copy_from_slice(&MAGIC);
    put_u32(&mut b, FILE_TYPE_OFFSET, FileType::MODEL);
    assert_eq!(parse(&b), Err(Rw4Error::ManifestTypeCode { found: 0 }));
}

#[test]
fn errors_render_usefully() {
    let mut b = Builder::default().build();
    put_u32(&mut b, FILE_TYPE_OFFSET, 0x1234_5678);
    assert_eq!(
        parse(&b).expect_err("bad file type").to_string(),
        "rw4: unknown file type 0x12345678"
    );
    assert_eq!(
        parse(&FIXTURE[..10]).expect_err("too short").to_string(),
        "rw4: record too short: 10 bytes, need at least 180"
    );
    let mut c = FIXTURE.to_vec();
    c[3] = 0x00;
    assert_eq!(
        parse(&c).expect_err("bad magic").to_string(),
        "rw4: bad magic at byte 3: found 0x00, want 0x34"
    );
}
