//! The DBPF v3 container layer: package index parsing, QFS decompression, and
//! record extraction.
//!
//! This is the first stage of the decode path described in
//! `docs/ASSET-PATH.md`. Everything downstream — the RW4 walker, the GMDL
//! walker, the asset manifest — addresses records through what this crate
//! returns, so the identity triple and the extent arithmetic here are the
//! foundation rather than a convenience.
//!
//! # What a package is
//!
//! A DBPF package is a 96-byte header, an index block, and then a pile of
//! record payloads at arbitrary offsets:
//!
//! ```text
//! 0x00  "DBPF"                    magic; "DBBF" is the 64-bit variant (rejected)
//! 0x04  major, minor              never read - "v3" is a convention
//! ...
//! 0x24  u32 index entry count
//! ...
//! 0x40  u32 index offset
//! ```
//!
//! The index block is a flags word, optional shared id words, then rows of
//! `20 + (type shared ? 0 : 4) + (group shared ? 0 : 4)` bytes — 28 in the
//! common case, 20 when both the type id and the group id are shared:
//!
//! ```text
//! flags u32
//!   bit 0 -> u32 shared type id       applies to every row
//!   bit 1 -> u32 shared group id      applies to every row
//!   bit 2 -> u32 shared instance id   PRESENT BUT NOT HONORED (see below)
//! row:
//!   u32 type id      (only when not shared)
//!   u32 group id     (only when not shared)
//!   u32 instance id
//!   u32 offset       absolute, from the start of the package
//!   u32 stored size  bit 31 is a flag, not a size bit - masked off on read
//!   u32 memory size  decompressed byte count
//!   u16 compression  0 = stored, 0xFFFF = QFS/RefPack, anything else: error
//!   u8  saved        carried, never interpreted
//!   u8  pad
//! ```
//!
//! # Three things that are easy to get wrong
//!
//! **The stored size's top bit is a flag.** Every row in
//! `tests/fixtures/mini_package.dbpf` stores `size | 0x8000_0000`. Without
//! [`SIZE_MASK`] a 16-byte record reads as `0x8000_0010` and every extent check
//! fails on a valid package.
//!
//! **The shared-instance word is skipped, not applied.** Index flag bit 2
//! announces a shared *instance* id. Both references step over those four bytes
//! and derive no row-size term from them. Honouring the word would substitute
//! one instance id for every row's own and silently change every record's
//! identity — the worst possible failure mode for a key-addressed store. See
//! [`INDEX_FLAG_SHARED_INSTANCE`].
//!
//! **The QFS decompressed size is big-endian.** It is the only big-endian field
//! in the format. See [`qfs`].
//!
//! # Divergences from the C++ reference
//!
//! `src/assets/Dbpf.cpp` is authoritative for the format. This port differs
//! from it in exactly three places, each deliberate:
//!
//! 1. **The `memory_size` invariant is enforced on the stored path too.** The
//!    C++ checks `out.size() != memSize` only after a QFS decompression
//!    (`Dbpf.cpp`, `extractDbpfRecord`). A row with `compression == 0` and
//!    `stored_size != memSize` returns `stored_size` bytes from the C++ and an
//!    error from here. Reason: on the stored path the two words describe the
//!    same bytes twice, so a disagreement is always corruption, and handing
//!    back a payload whose length disagrees with the index is exactly the
//!    silent-wrong-answer this repository is built to avoid.
//! 2. **The size check moves ahead of the copy for the compressed path too**,
//!    which is only a reordering of the same two operations.
//! 3. **No error string is a bare "truncated header".** That C++ branch is
//!    unreachable (see [`DbpfError`]), so it is not reproduced as an
//!    unreachable variant.
//!
//! The Python oracle (`tools/spore/dbpf/dbpf.py`) differs in ways this port
//! does **not** follow, because it is the cross-check and not the
//! specification:
//!
//! * it accepts `DBBF` and parses 8-byte offsets; here `DBBF` is refused;
//! * it treats any `compression != 0xFFFF` as "stored"; here anything outside
//!   `{0, 0xFFFF}` is a hard error;
//! * its `qfs_decompress` performs no bounds checks at all — a Python negative
//!   index silently wraps and a short `bytearray` raises `IndexError` — where
//!   this decoder returns typed errors.
//!
//! # Clean-room boundary
//!
//! Nothing here is derived from EA/Maxis code. The layout is reimplemented from
//! format analysis: the community-documented DBPF spec (transcribed in
//! `dbpf.py`), the `10 FB` / 24-bit-size QFS header, and the Sims2Wiki DBPF
//! compression page its docstring cites. `tests/fixtures/mini_package.dbpf` is a
//! committed synthetic fixture generated by
//! `tests/fixtures/gen_fixtures.py`; the C++ and Python implementations above
//! are OpenSpore's own.
//!
//! # Testing
//!
//! Every unit test lives next to the code it covers. The fixture-driven and
//! encoder round-trip tests are integration tests in `tests/`, because they read
//! `tests/fixtures/mini_package.dbpf` from the repository root and need a
//! synthetic QFS *encoder* that has no business in the decoder.

#![forbid(unsafe_code)]
#![warn(missing_debug_implementations)]

mod cursor;
mod entry;
mod error;
mod extract;
mod index;
mod qfs;

pub use crate::entry::{DbpfEntry, COMPRESSION_NONE, COMPRESSION_QFS, MAGIC, MAGIC_64};
pub use crate::error::DbpfError;
pub use crate::extract::extract_record;
pub use crate::index::{
    find_entry, parse_index, PackageIndex, HEADER_SIZE, INDEX_FLAG_SHARED_GROUP,
    INDEX_FLAG_SHARED_INSTANCE, INDEX_FLAG_SHARED_TYPE, OFF_INDEX_COUNT, OFF_INDEX_OFFSET,
    ROW_SIZE_BOTH_SHARED, ROW_SIZE_PLAIN, SIZE_MASK,
};
pub use crate::qfs::{
    decompress, is_supported_compression, QFS_HEADER_SIZE, QFS_MAGIC, QFS_MAGIC_VARIANTS,
};
