#!/usr/bin/env python3
"""Deterministic synthetic test fixtures for OpenSpore format tests.

Generates (no timestamps, no randomness):
  tests/fixtures/mini_package.dbpf  DBPF v3, 3 records: 1 uncompressed, 1 QFS-compressed, 1 uncompressed
  tests/fixtures/mini_rw4.rw4       RW4 container: BaseResource + Raster + Mesh sections
  tests/fixtures/mini.gmdl          GMDL version 8, one mesh (153 u16 indices, 50 vertices)

Re-running the script over existing fixtures fails loudly if bytes would differ,
so the committed fixtures stay reproducible.
"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def pack_u32(v):
    return struct.pack('<I', v)


def write_if_identical(path, blob):
    if os.path.exists(path):
        with open(path, 'rb') as f:
            if f.read() != blob:
                sys.exit(f"FATAL: {os.path.basename(path)} on disk differs from regenerated bytes "
                         f"(expected deterministic generator); delete it and re-run")
        print(f"  {os.path.basename(path)}: identical ({len(blob)} bytes)")
        return
    with open(path, 'wb') as f:
        f.write(blob)
    print(f"  {os.path.basename(path)}: written ({len(blob)} bytes)")


# ---------------------------------------------------------------- DBPF

# 112 distinct bytes (one big-literal token) + 300 zeros (2 big-literal tokens + 19 small tokens)
QFS_PAYLOAD = bytes(range(112)) + b'\x00' * 300  # 412 bytes
REC0 = bytes(range(16))
REC2 = bytes((i * 7) & 0xFF for i in range(64))


def qfs_compress(payload):
    """Greedy encoder for the EA QFS token grammar (inverse of dbpf.qfs_decompress).

    Token classes used:
      c 1..127   : npd = c&3 literal bytes, then ntc = ((c&0x1C)>>2)+3 copies of the
                   last written byte (co = 1 when c&0x60 == 0). A c=1 token therefore
                   consumes 4 identical input bytes: 1 literal + 3 copies.
      c 224..251 : npd = ((c&0x1F)<<2)+4 literal bytes (4..112), no copies (arbitrary).
    A trailing 1-3 byte tail is not encodable by this encoder (raise).
    """
    assert len(payload) <= 0xFFFFFF
    if len(payload) < 4 and len(payload) != 0:
        raise ValueError("QFS encoder: payload shorter than 4 bytes not encodable")
    out = bytearray([0x10, 0xFB])
    out += len(payload).to_bytes(3, 'big')
    i, n = 0, len(payload)
    while i < n:
        run = 1
        while i + run < n and payload[i + run] == payload[i]:
            run += 1
        if run >= 4 and run % 4 == 0:
            rem = run
            while rem > 112:
                out.append(224 + ((112 - 4) >> 2))
                out += payload[i:i + 112]
                i += 112
                rem -= 112
            if rem % 4 == 0:
                for _ in range(rem // 4):
                    out.append(1)
                    out.append(0)
                    out.append(payload[i])
                    i += 4
            else:
                out.append(224 + ((rem - 4) >> 2))
                out += payload[i:i + rem]
                i += rem
        else:
            while i < n:
                take = min(112, n - i)
                if take < 4:
                    raise ValueError(f"QFS encoder: tail of {take} bytes at {i} not encodable")
                out.append(224 + ((take - 4) >> 2))
                out += payload[i:i + take]
                i += take
    return bytes(out)


def dbpf_item(t, g, inst, off, csize, msize, comp):
    return struct.pack('<IIIIIIHBB', t, g, inst, off, csize | 0x80000000, msize,
                       0xFFFF if comp else 0, 0, 0)


def build_package():
    recs = [
        # (typeID 4CC, group, instance, payload, compressed?)
        (0x58545354, 0x11111111, 0x22222222, REC0, False),       # 4CC 'TSTX'
        (0x31534651, 0x33333333, 0x44444444, QFS_PAYLOAD, True),  # 4CC 'QFS1'
        (0x42574152, 0x55555555, 0x66666666, REC2, False),        # 4CC 'RAWB'
    ]
    idx_start = 100  # 96-byte header + 4-byte index flags
    off = idx_start + len(recs) * 28
    blobs, items = [], []
    for t, g, inst, payload, comp in recs:
        raw = qfs_compress(payload) if comp else payload
        items.append(dbpf_item(t, g, inst, off, len(raw), len(payload), comp))
        blobs.append(raw)
        off += len(raw)
    hdr = struct.pack('<4sII', b'DBPF', 3, 0)
    hdr += b'\x00' * 20
    hdr += struct.pack('<II', 3, len(items))
    hdr += b'\x00' * 4
    hdr += struct.pack('<I', len(items) * 28)
    hdr += b'\x00' * 12
    hdr += struct.pack('<II', 3, 96)
    hdr += b'\x00' * 28
    assert len(hdr) == 96
    return hdr + b'\x00' * 4 + b''.join(items) + b''.join(blobs)


# ---------------------------------------------------------------- RW4

RW4_MAGIC = bytes([0x89, 0x52, 0x57, 0x34, 0x77, 0x33, 0x32, 0x00, 0x0D, 0x0A, 0x1A, 0x0A,
                   0x00, 0x20, 0x04, 0x00, 0x34, 0x35, 0x34, 0x00, 0x30, 0x30, 0x30, 0x00,
                   0x00, 0x00, 0x00, 0x00])

RST_W, RST_H, RST_FMT = 4, 2, 3
RST_TEXELS = struct.pack(f'<{RST_W * RST_H}I',
                         *[(x * 13 + y * 7) & 0xFF for y in range(RST_H) for x in range(RST_W)])
MESH_VTX = 4
MESH_IDX = (0, 1, 2, 0, 2, 3)


def build_rw4():
    base = struct.pack('<III', 0x11223344, 0x55667788, 0x00E6BCE5)
    raster = struct.pack('<III', RST_W, RST_H, RST_FMT) + RST_TEXELS
    mesh = struct.pack('<III', MESH_VTX, len(MESH_IDX), len(MESH_IDX) * 2) \
        + struct.pack(f'<{len(MESH_IDX)}H', *MESH_IDX)
    assert len(base) == 12 and len(raster) == 44 and len(mesh) == 24

    off_base, off_raster, off_mesh = 0x138, 0x144, 0x170
    buf_size = 0x188 - off_base
    b = bytearray(0x188)
    b[0x00:0x1C] = RW4_MAGIC
    struct.pack_into('<I', b, 0x1C, 1)              # ftype MODEL
    struct.pack_into('<I', b, 0x20, 1)              # objCount
    struct.pack_into('<I', b, 0x24, 3)              # sectionCount
    struct.pack_into('<I', b, 0x30, 0x0F0)          # pSectionInfo
    struct.pack_into('<I', b, 0x44, off_base)       # pBufferData
    struct.pack_into('<I', b, 0x4C, buf_size)       # bufSize
    struct.pack_into('<7I', b, 0x98, 0x10004, 0, 0, 0x1C, 0x34, 0x40, 0x4C)  # manifest
    struct.pack_into('<5I', b, 0x0B4, 0x10005, 3, 0x10030, 0x20003, 0x40001)  # types
    struct.pack_into('<II', b, 0x0CC, 0x10006, 0)   # external arenas
    struct.pack_into('<II', b, 0x0D8, 0x10007, 0)   # sub refs
    struct.pack_into('<II', b, 0x0E4, 0x10008, 0)   # atoms
    struct.pack_into('<6I', b, 0x0F0, 0, 0, len(base), 1, 0, 0x10030)
    struct.pack_into('<6I', b, 0x0F0 + 24, off_raster, 0, len(raster), 1, 1, 0x20003)
    struct.pack_into('<6I', b, 0x0F0 + 48, off_mesh, 0, len(mesh), 1, 2, 0x40001)
    b[off_base:off_base + len(base)] = base
    b[off_raster:off_raster + len(raster)] = raster
    b[off_mesh:off_mesh + len(mesh)] = mesh
    return bytes(b)


# ---------------------------------------------------------------- GMDL

GMDL_BBOX_MIN = (1.5, -2.25, 0.125)
GMDL_BBOX_MAX = (3.5, 0.75, 2.0)
GMDL_RADIUS = 4.25
GMDL_IDX_COUNT = 153
GMDL_VTX_COUNT = 50
GMDL_STRIDE = 16


def build_gmdl():
    idx = [(i * 17) % GMDL_VTX_COUNT for i in range(GMDL_IDX_COUNT)]
    vtx = bytes((i * 7 + (i % GMDL_STRIDE) * 3) & 0xFF for i in range(GMDL_VTX_COUNT * GMDL_STRIDE))
    b = struct.pack('<I', 8) + struct.pack('>I', 1)  # refCount is big-endian
    b += struct.pack('<III', 0x11111111, 0x22222222, 0x00E6BCE5)  # referenced file key
    b += struct.pack('<I', 1)                                      # meshCount
    b += struct.pack('<6f', *GMDL_BBOX_MIN, *GMDL_BBOX_MAX)
    b += struct.pack('<f', GMDL_RADIUS)
    b += struct.pack('<I', 1)
    b += struct.pack('<IIII', 4, GMDL_IDX_COUNT, 16, GMDL_IDX_COUNT * 2)
    b += struct.pack(f'<{GMDL_IDX_COUNT}H', *idx)
    b += struct.pack('<I', 1)                                      # numVertexDescriptors
    b += struct.pack('<I', 2)                                      # elementCount
    b += struct.pack('<HHBBBBI', 0, 0, 2, 0, 0, 0, 0)              # POSITION FLOAT3 @0
    b += struct.pack('<HHBBBBI', 0, 8, 1, 0, 5, 0, 0)              # TEXCOORD0 FLOAT2 @8
    b += struct.pack('<I', 1)                                      # numVertexBuffers
    b += struct.pack('<III', 0, GMDL_VTX_COUNT, len(vtx))
    b += vtx
    b += struct.pack('<II', 0, 0)                                  # mesh: idxBuf 0, vtxBuf 0
    b += struct.pack('<I', 0x12345678)                             # materialID
    b += struct.pack('<I', 0)                                      # unk
    b += struct.pack('<I', 0)                                      # materialInfoCount
    b += struct.pack('<I', 0)                                      # boneRangeCount
    b += struct.pack('<I', 0)                                      # animDataCount
    b += struct.pack('<III', 0, 0, 0)                              # unknownKey
    return bytes(b)


def main():
    os.makedirs(HERE, exist_ok=True)
    write_if_identical(os.path.join(HERE, 'mini_package.dbpf'), build_package())
    write_if_identical(os.path.join(HERE, 'mini_rw4.rw4'), build_rw4())
    write_if_identical(os.path.join(HERE, 'mini.gmdl'), build_gmdl())
    print("fixtures OK")
    return 0


if __name__ == '__main__':
    sys.exit(main())
