#!/usr/bin/env python3
"""Deterministic generator for the ABI-inference fixture corpus.

Writes (no timestamps, no randomness):
  tests/fixtures/abi/<nn>_<slug>.asm   Intel-syntax instruction streams
  tests/fixtures/abi/<nn>_<slug>.att   the AT&T twin of fixture 01
  tests/expected/abi/<nn>_<slug>.json  the engine's record for each input

Re-running over existing inputs fails loudly if the bytes would differ, so the
committed fixtures stay reproducible. Delete a fixture and re-run to regenerate
it. Golden re-recording is a separate, explicit step:

    python3 tests/fixtures/gen_abi_fixtures.py            # inputs only, FATAL on drift
    python3 tests/fixtures/gen_abi_fixtures.py --record   # also re-record goldens

The `write_if_identical` guard mirrors tests/fixtures/gen_fixtures.py, which is
the house pattern. `--record` is the only way a golden can change: it makes the
engine's current output the new expectation, so a deliberate engine change and
an accidental one are equally easy to perform. The suite is what catches the
accident, because every expectation is compared with a full semantic diff.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from tests import abi_fixtures as fx  # noqa: E402
from tools.reconstruction_tooling import abi_infer  # noqa: E402
from tools.reconstruction_tooling.models import canonical_json  # noqa: E402


def write_if_identical(path, blob, force=False):
    """Write `blob` to `path`; refuse to silently change existing bytes."""
    name = os.path.basename(path)
    if os.path.exists(path):
        with open(path, "rb") as handle:
            current = handle.read()
        if current != blob:
            if not force:
                sys.exit("FATAL: %s on disk differs from regenerated bytes "
                         "(expected deterministic generator); delete it and re-run, "
                         "or pass --record if the engine's record really changed"
                         % name)
            print("  %s: rewritten (%d bytes)" % (name, len(blob)))
            with open(path, "wb") as handle:
                handle.write(blob)
            return
        print("  %s: identical (%d bytes)" % (name, len(blob)))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(blob)
    print("  %s: written (%d bytes)" % (name, len(blob)))


def record_for(text, image_base=0x00400000):
    return abi_infer.analyze(text, image_base=image_base)


def main(argv):
    record_mode = "--record" in argv
    unknown = [item for item in argv if item != "--record"]
    if unknown:
        sys.exit("FATAL: unknown argument(s): %s" % " ".join(unknown))

    os.makedirs(fx.FIXTURE_DIR, exist_ok=True)
    os.makedirs(fx.EXPECT_DIR, exist_ok=True)

    print("inputs (%d):" % len(fx.FIXTURES))
    for fixture in fx.FIXTURES:
        path = os.path.join(fx.FIXTURE_DIR, fixture.name)
        write_if_identical(path, fixture.blob, force=record_mode)

    if not record_mode:
        missing = [fixture.name for fixture in fx.FIXTURES
                   if not os.path.isfile(os.path.join(fx.FIXTURE_DIR, fixture.name))]
        if missing:
            sys.exit("FATAL: %d fixture(s) missing after generation: %s"
                     % (len(missing), ", ".join(missing)))
        print("inputs OK (%d, byte-identical)" % len(fx.FIXTURES))
        return 0

    print("goldens:")
    written = 0
    for fixture in fx.FIXTURES:
        if fixture.stem == fx.ATT_TWIN_OF:
            # The AT&T twin is asserted against fixture 01's golden modulo the
            # documented provenance keys, so it gets no golden of its own.
            continue
        record = record_for(fixture.text())
        blob = canonical_json(record).encode("utf-8")
        path = os.path.join(fx.EXPECT_DIR, fixture.stem + ".json")
        write_if_identical(path, blob, force=True)
        written += 1
    print("recorded %d golden(s) -> tests/expected/abi/" % written)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
