#!/usr/bin/env python3
"""Embed compiled .spv files as uint32_t C arrays in a header.

Usage: embed_spv.py <vert.spv> <frag.spv> <out.h>
Clean-room build helper, no third-party code.
"""
import struct
import sys


def emit(name, path, out):
    with open(path, "rb") as f:
        data = f.read()
    if len(data) % 4 != 0:
        raise SystemExit(f"{path}: SPIR-V size {len(data)} is not a multiple of 4")
    words = struct.unpack(f"<{len(data) // 4}I", data)
    out.write(f"static const uint32_t {name}[{len(words)}] = {{\n")
    for i in range(0, len(words), 4):
        chunk = ", ".join(f"0x{w:08x}u" for w in words[i : i + 4])
        out.write(f"    {chunk},\n")
    out.write("};\n")
    out.write(f"static const size_t {name}WordCount = {len(words)};\n\n")


def main():
    vert, frag, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(out_path, "w") as out:
        out.write("// Generated by embed_spv.py — do not edit.\n")
        out.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
        emit("kTriangleVertSpv", vert, out)
        emit("kTriangleFragSpv", frag, out)


if __name__ == "__main__":
    main()
